# Generated by Django 2.0 on 2018-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
