# Generated by Django 2.0 on 2018-11-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringsubject',
            name='subject_type',
            field=models.CharField(choices=[('Q', '小考'), ('H', '作業')], max_length=2, null=True),
        ),
    ]
