# Generated by Django 2.0 on 2018-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20181109_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringsubject',
            name='subject_type',
            field=models.CharField(choices=[('Q', '小考'), ('H', '作業')], max_length=2, null=True),
        ),
    ]
