# Generated by Django 2.0 on 2018-11-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20181110_1849'),
        ('course', '0004_auto_20181105_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers_responsible',
            field=models.ManyToManyField(to='staff.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoringsubject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoringsubject',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
