# Generated by Django 2.0 on 2018-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_scoringsubject_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registered_students',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
