# Generated by Django 2.0 on 2018-11-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20181110_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers_responsible',
        ),
    ]
