# Generated by Django 2.0 on 2018-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20181117_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
