# Generated by Django 2.0 on 2018-09-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('cellphone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('role_field', models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Professor'), (3, 'Staff'), (4, 'Admin')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
