# Generated by Django 2.0 on 2018-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0002_auto_20180927_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_field',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Professor'), (3, 'Staff'), (4, 'Admin')], default=1),
        ),
    ]
