# Generated by Django 2.0 on 2018-09-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0003_auto_20180927_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
