# Generated by Django 2.0 on 2018-10-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0004_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
