# Generated by Django 2.0 on 2018-10-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0005_auto_20181005_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_field',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Professor'), (3, 'Executive'), (4, 'Admin')], default=1),
        ),
    ]
