# Generated by Django 2.0 on 2018-10-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0006_auto_20181005_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cellphone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leave_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered_date',
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='123', max_length=50, unique=True),
        ),
    ]
