# Generated by Django 2.0 on 2018-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0007_auto_20181023_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_field',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Executive'), (4, 'Admin')], default=1),
        ),
    ]
