# Generated by Django 2.0 on 2018-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181109_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
